name: hi_gas
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

# dependencies
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  iconsax_flutter: ^1.0.0
  smooth_page_indicator: ^1.2.0+3
  pinput: ^5.0.0
  geolocator: ^13.0.2
  google_maps_flutter: ^2.10.0
  location: ^7.0.1
  intl: ^0.19.0
  provider: ^6.1.2
  geocoding: ^3.0.0
  timelines: ^0.1.0
  image_picker: ^1.1.2
  permission_handler: ^11.0.0



# The following section is specific to Flutter.
dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.0


flutter:

  uses-material-design: true


  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
  #   - images/a_dot_ham.jpeg


  fonts:
    - family: SpaceGrotesk
      fonts:
        - asset: assets/fonts/SpaceGrotesk-VariableFont_wght.ttf
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
